# Generated by Django 5.1.6 on 2025-04-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Retailer',
        ),
        migrations.DeleteModel(
            name='VendorReview',
        ),
    ]
