# Generated by Django 5.1.6 on 2025-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_range',
            field=models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$', max_length=20),
        ),
    ]
