# Generated by Django 4.2 on 2025-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_hotel_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='items',
            field=models.TextField(blank=True, help_text='List of items offered (comma-separated)'),
        ),
        migrations.AddField(
            model_name='gym',
            name='special_items',
            field=models.TextField(blank=True, help_text='List of special items (comma-separated)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='items',
            field=models.TextField(blank=True, help_text='List of items offered (comma-separated)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='special_items',
            field=models.TextField(blank=True, help_text='List of special items (comma-separated)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='items',
            field=models.TextField(blank=True, help_text='List of items offered (comma-separated)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_items',
            field=models.TextField(blank=True, help_text='List of special items (comma-separated)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='items',
            field=models.TextField(blank=True, help_text='List of items offered (comma-separated)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='special_items',
            field=models.TextField(blank=True, help_text='List of special items (comma-separated)'),
        ),
        migrations.AddField(
            model_name='retailstore',
            name='items',
            field=models.TextField(blank=True, help_text='List of items offered (comma-separated)'),
        ),
        migrations.AddField(
            model_name='retailstore',
            name='special_items',
            field=models.TextField(blank=True, help_text='List of special items (comma-separated)'),
        ),
    ]
