# Generated by Django 5.1.6 on 2025-04-18 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_vendor_retailer_delete_vendorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym', to='myapp.retailer'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='myapp.retailer'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='myapp.retailer'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='myapp.retailer'),
        ),
        migrations.AddField(
            model_name='retailstore',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail', to='myapp.retailer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('retailer', 'Retailer')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to=settings.AUTH_USER_MODEL),
        ),
    ]
