# Generated by Django 5.1.6 on 2025-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_restaurant_rating_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='000000000000', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use_profile_image',
            field=models.ImageField(default='00000000000', upload_to='profile'),
            preserve_default=False,
        ),
    ]
