# Generated by Django 5.1.6 on 2025-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_hotel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
