# Generated by Django 5.1.6 on 2025-04-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gym_retailer_hospital_retailer_hotel_retailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='myapp.retailer'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='myapp.retailer'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='myapp.retailer'),
        ),
        migrations.AlterField(
            model_name='retailstore',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_stores', to='myapp.retailer'),
        ),
    ]
