# Generated by Django 5.1.6 on 2025-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_gym_retailer_alter_hospital_retailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='retailstore',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
