# Generated by Django 5.1.6 on 2025-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gym_status_hospital_status_hotel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailstore',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the store'),
        ),
        migrations.AddField(
            model_name='retailstore',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number of the store', max_length=15, null=True),
        ),
    ]
