# Generated by Django 5.1.6 on 2025-03-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_contact_gym_hospital_retailstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='profile_picture',
        ),
    ]
